version: '3.9'

services:
 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - 3031:3031
    volumes:
      - .:/var/www/my-react-app
      - ./config:/ect/nginx/conf.d