export enum Sign {
    SIGNIN_REQUEST = "SIGNIN_REQUEST",
    SIGNIN_SUCCESS= "SIGNIN_SUCCESS",
    SIGNIN_FAIL= "SIGNIN_FAIL",
    SIGN_OUT= "SIGN_OUT",
    SIGN_UP_REQUEST = "SIGN_UP_REQUEST",
    SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
    SIGN_UP_FAIL = "SIGN_UP_FAIL",
}
 export enum EProduct {
    PRODUCT_REQUEST = "PRODUCT_REQUEST",
    PRODUCT_SUCCESS= "PRODUCT_SUCCESS",
    PRODUCT_FAIL= "PRODUCT_FAIL"
}

export enum ERole {
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_USER = "ROLE_USER",
    ROLE_MODERATOR = "ROLE_MODERATOR"
}