export enum Sign {
    SIGNIN_REQUEST = "SIGNIN_REQUEST",
    SIGNIN_SUCCESS= "SIGNIN_SUCCESS",
    SIGNIN_FAIL= "SIGNIN_FAIL",
    SIGN_OUT= "SIGN_OUT"
}
 export enum EProduct {
    PRODUCT_REQUEST = "PRODUCT_REQUEST",
    PRODUCT_SUCCESS= "PRODUCT_SUCCESS",
    PRODUCT_FAIL= "PRODUCT_FAIL"
}

